--LAB_4A (ALTER)

ALTER TABLE DEPOSIT
ADD CITY VARCHAR(20),
	PINCODE INT

ALTER TABLE DEPOSIT ALTER COLUMN CNAME VARCHAR(35)

ALTER TABLE DEPOSIT ALTER COLUMN AMOUNT INT

EXEC SP_RENAME 'DEPOSIT_DETAIL.ACTNO',ANO;

ALTER TABLE DEPOSIT_DETAIL DROP COLUMN CITY
SELECT *FROM DEPOSIT_DETAIL

EXEC SP_RENAME 'DEPOSIT','DEPOSIT_DETAIL'



--LAB_4B

EXEC SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE'

ALTER TABLE DEPOSIT_DETAIL DROP COLUMN AOPENDATE

EXEC SP_RENAME 'DEPOSIT_DETAIL.CNAME','CUSTOMERNAME'

--LAB_4C

CREATE TABLE STUDENT_DETAIL(
COLUMN_NAME VARCHAR(50),
DATATYPE VARCHAR(50),
);


--LAB 4_C 

CREATE TABLE STUDENT_DETAIL(
Enrollment_No VARCHAR(20),
Name VARCHAR(25),
CPI DECIMAL(5,2),
Birthdate DATETIME
);

SELECT * FROM STUDENT_DETAIL

ALTER TABLE STUDENT_DETAIL ADD CITY VARCHAR(20) NOT NULL,BACKLOG INT NULL

ALTER TABLE STUDENT_DETAIL ALTER COLUMN NAME VARCHAR(35)

ALTER TABLE STUDENT_DETAIL ALTER COLUMN CPI INT

EXEC SP_RENAME 'STUDENT_DETAIL.Enrollment_No','EMO'

EXEC SP_RENAME 'STUDENT_DETAIL',' STUDENT_MASTER'

ALTER TABLE STUDENT_MASTER DROP COLUMN CITY


---DELETE, Truncate, Drop Operation

CREATE TABLE DEPOSIT_DETAIL(
ANO INT,
CustomerName VARCHAR(35),
BNAME VARCHAR(50),
AMOUNT INT,
PINCODE INT
);

SELECT * FROM DEPOSIT_DETAIL

DELETE FROM DEPOSIT_DETAIL WHERE AMOUNT >=4000

DELETE FROM DEPOSIT_DETAIL WHERE BNAME='CHANDI'

DELETE FROM DEPOSIT_DETAIL WHERE ANO>106

TRUNCATE TABLE DEPOSIT_DETAIL;

DROP TABLE DEPOSIT_DETAIL;

--B-PART

CREATE TABLE EMPLOYEE_MASTER(
EmpNo INT,
EmpName VARCHAR(25),
JoiningDate DATETIME,
Salary DECIMAL(8,2),
City VARCHAR(20)
);

SELECT * FROM EMPLOYEE_MASTER

INSERT INTO EMPLOYEE_MASTER VALUES(101,'Keyur','02-01-05',12000.00,'Rajkot')
INSERT INTO EMPLOYEE_MASTER VALUES(102,'Hardik','04-02-15',14000.00,'Ahmedabad')
INSERT INTO EMPLOYEE_MASTER VALUES(103,'Kajal','06-03-14',15000.00,'Baroda')
INSERT INTO EMPLOYEE_MASTER VALUES(104,'Bhoomi','05-06-23',12500.00,'Ahmedabad')
INSERT INTO EMPLOYEE_MASTER VALUES(105,'Harmit','04-02-15',14000.00,'Rajkot')
INSERT INTO EMPLOYEE_MASTER VALUES(106,'Mitesh','01-09-25',5000.00,'Jamnagar')
INSERT INTO EMPLOYEE_MASTER VALUES(107,'Meera',Null,7000.00,'Morbi')
INSERT INTO EMPLOYEE_MASTER VALUES(108,'Kishan','03-02-06',10000.00,NULL);

DELETE FROM EMPLOYEE_MASTER WHERE Salary>=14000

DELETE FROM EMPLOYEE_MASTER WHERE CITY='RAJKOT'

DELETE FROM EMPLOYEE_MASTER WHERE JoiningDate>'01-01-2007'

DELETE FROM EMPLOYEE_MASTER WHERE JoiningDate IS NULL

DELETE FROM EMPLOYEE_MASTER WHERE Salary=20000*0.5

DELETE FROM EMPLOYEE_MASTER WHERE CITY is not null

TRUNCATE TABLE EMPLOYEE_MASTER

DROP TABLE EMPLOYEE_MASTER--LAB_4A (ALTER)

ALTER TABLE DEPOSIT ADD CITY VARCHAR(20),PINCODE INT

ALTER TABLE DEPOSIT ALTER COLUMN CNAME VARCHAR(35)

ALTER TABLE DEPOSIT ALTER COLUMN AMOUNT INT

SP_RENAME 'DEPOSIT_DETAIL.ACTNO',ANO;

ALTER TABLE DEPOSIT_DETAIL DROP COLUMN CITY
SELECT *FROM DEPOSIT_DETAIL

SP_RENAME DEPOSIT,DEPOSIT_DETAIL;


--LAB_4B

SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE'

ALTER TABLE DEPOSIT_DETAIL DROP COLUMN AOPENDATE

SP_RENAME 'DEPOSIT_DETAIL.CNAME','CUSTOMERNAME'

--LAB_4C

CREATE TABLE STUDENT_DETAIL(
COLUMN_NAME VARCHAR(50),
DATATYPE VARCHAR(50),
);


--LAB 4_C 

CREATE TABLE STUDENT_DETAIL(
Enrollment_No VARCHAR(20),
Name VARCHAR(25),
CPI DECIMAL(5,2),
Birthdate DATETIME
);

SELECT * FROM STUDENT_DETAIL

ALTER TABLE STUDENT_DETAIL ADD CITY VARCHAR(20) NOT NULL,BACKLOG INT NULL

ALTER TABLE STUDENT_DETAIL ALTER COLUMN NAME VARCHAR(35)

ALTER TABLE STUDENT_DETAIL ALTER COLUMN CPI INT

SP_RENAME 'STUDENT_DETAIL.Enrollment_No','EMO'

SP_RENAME 'STUDENT_DETAIL',' STUDENT_MASTER'

ALTER TABLE STUDENT_DETAIL DROP COLUMN CITY


---DELETE, Truncate, Drop Operation

CREATE TABLE DEPOSIT_DETAIL(
ANO INT,
CustomerName VARCHAR(35),
BNAME VARCHAR(50),
AMOUNT INT,
PINCODE INT
);

SELECT * FROM DEPOSIT_DETAIL

DELETE FROM DEPOSIT_DETAIL WHERE AMOUNT >=4000

DELETE FROM DEPOSIT_DETAIL WHERE BNAME='CHANDI'

DELETE FROM DEPOSIT_DETAIL WHERE ANO>106

TRUNCATE TABLE DEPOSIT_DETAIL;

DROP TABLE DEPOSIT_DETAIL;

--B-PART

CREATE TABLE EMPLOYEE_MASTER(
EmpNo INT,
EmpName VARCHAR(25),
JoiningDate DATETIME,
Salary DECIMAL(8,2),
City VARCHAR(20)
);

SELECT * FROM EMPLOYEE_MASTER

INSERT INTO EMPLOYEE_MASTER VALUES(101,'Keyur','02-01-05',12000.00,'Rajkot')
INSERT INTO EMPLOYEE_MASTER VALUES(102,'Hardik','04-02-15',14000.00,'Ahmedabad')
INSERT INTO EMPLOYEE_MASTER VALUES(103,'Kajal','06-03-14',15000.00,'Baroda')
INSERT INTO EMPLOYEE_MASTER VALUES(104,'Bhoomi','05-06-23',12500.00,'Ahmedabad')
INSERT INTO EMPLOYEE_MASTER VALUES(105,'Harmit','04-02-15',14000.00,'Rajkot')
INSERT INTO EMPLOYEE_MASTER VALUES(106,'Mitesh','01-09-25',5000.00,'Jamnagar')
INSERT INTO EMPLOYEE_MASTER VALUES(107,'Meera',Null,7000.00,'Morbi')
INSERT INTO EMPLOYEE_MASTER VALUES(108,'Kishan','03-02-06',10000.00,NULL);

DELETE FROM EMPLOYEE_MASTER WHERE Salary>=14000

DELETE FROM EMPLOYEE_MASTER WHERE CITY='RAJKOT'

DELETE FROM EMPLOYEE_MASTER WHERE JoiningDate>'01-01-2007'

DELETE FROM EMPLOYEE_MASTER WHERE JoiningDate IS NULL

DELETE FROM EMPLOYEE_MASTER WHERE Salary=20000*0.5

DELETE FROM EMPLOYEE_MASTER WHERE CITY is not null

TRUNCATE TABLE EMPLOYEE_MASTER

DROP TABLE EMPLOYEE_MASTER