--Retrieve all data from table DEPOSIT
SELECT * FROM DEPOSIT

SELECT * FROM BORROW

SELECT * FROM CUSTOMERS

SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT

SELECT LOANNO,AMOUNT FROM BORROW

SELECT LOANNO,AMOUNT FROM BORROW
WHERE BNAME='ANDHERI'

SELECT ACTNO,AMOUNT FROM DEPOSIT
WHERE ACTNO=106

SELECT AMOUNT,CNAME FROM BORROW
WHERE AMOUNT>5000

SELECT CNAME FROM DEPOSIT 
WHERE ADATE>'1996-12-01'

SELECT BNAME,ACTNO FROM DEPOSIT 
WHERE ACTNO<105

SELECT CNAME,CITY FROM CUSTOMERS 
WHERE CITY='NAGPUR' OR CITY='DELHI'

SELECT CNAME,BNAME,AMOUNT FROM DEPOSIT 
WHERE AMOUNT>4000 AND ACTNO<105

SELECT CNAME,BNAME FROM BORROW WHERE 
AMOUNT>=3000 AND AMOUNT<=8000

SELECT CNAME FROM BORROW WHERE 
AMOUNT BETWEEN 3000 AND 8000

SELECT*FROM DEPOSIT 
WHERE NOT BNAME='ANDHERI'

SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT
WHERE BNAME IN ('AJNI','KAROLBAGH','M.G.ROAD') AND ACTNO<104

SELECT TOP 5*FROM DEPOSIT 

SELECT TOP 3*FROM DEPOSIT
WHERE AMOUNT>1000

SELECT TOP 5 LOANNO,CNAME FROM BORROW 
WHERE NOT BNAME='ANDHERI'

SELECT DISTINCT CITY FROM CUSTOMERS

SELECT DISTINCT BNAME FROM BRANCH

SELECT TOP 50 PERCENT*FROM BORROW

SELECT TOP 10 PERCENT AMOUNT FROM DEPOSIT

SELECT TOP 25 PERCENT*FROM DEPOSIT 
WHERE AMOUNT>5000

SELECT TOP 10 PERCENT AMOUNT FROM BORROW

SELECT DISTINCT * FROM CUSTOMERS

SELECT *,AMOUNT+(AMOUNT*0.1) AS INC FROM BORROW

SELECT*FROM BORROW WHERE LOANNO%2=0
SELECT*FROM BORROW WHERE LOANNO%2=1

--retrive all the records of customer table
select*from CUSTOMERS

--RETRIVE ALL ELEMENT THE RECORDS OF DEPOSIT TABLE WHITOUT USING *
--SELECT COLUMN NAME FROM DEPOSIT

--DISPLAY TOP 3 UNIQUE CITY OF BRANCH TABLE
SELECT DISTINCT TOP 3 CITY FROM BRANCH

--FIND TOP 50 PERCENT RECORD OF CUSTOMER TABLE
SELECT TOP 50 PERCENT*FROM CUSTOMERS